### ISSUE TITLE
 on iOS does not work very well

### ISSUE THREAD

**Issue by vico-aguado** [leisim/logger#1]
Hi!!

I try in iOS and the log show this:

│ #1   _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄\^[[<…>
flutter: │ 🐛 Log message with 2 methods\^[[<…>
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────\^[[<…>
flutter: \^[[38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;12m│ 💡 Info message<…>
flutter: \^[[38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;208m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;208m│ ⚠️ Just a warning!<…>
flutter: \^[[38;5;208m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ \^[[0m\^[[39m\^[[48;5;196mTest Error<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ #0   MyTicketsPage.build.() (package:_app/src/sections/my_page.dart:55:3<…>
flutter: \^[[38;5;196m│ #1   _FutureBuilderState.build (package:flutter/src/widgets/async.dar<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ Error! Something bad happened<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;199m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;199m│ #0   MyTicketsPage.build.() (package:_app/src/sections/my_page.dart:57:3<…>
flutter: \^[[38;5;199m│ #1   _FutureBuilderState.build (package:flutter/src/widgets/async.dar<…>
flutter: \^[[38;5;199m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;199m│ 👾 What a terrible failure log<…>
flutter: \^[[38;5;199m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>

**Comment by leisim** [comment]
Oh no, I didn't try it on iOS yet.

Do you use Xcode or VSCode?

**Comment by vico-aguado** [comment]
I use both, but more often VSCode

**Comment by leisim** [comment]
And do you see this problem in Xcode or VSCode?

Xcode does not support colors but in VSCode it should work fine.

**Comment by vico-aguado** [comment]
I ser this problem in both :(

**Comment by leisim** [comment]
Okay thank you! I'll test it.

**Comment by leisim** [comment]
I may take a little longer to fix this problem. In the meantime I added a parameter to the `PrettyPrinter` to disable colors.

**Comment by priezz** [comment]
@leisim Any progress on that? Package is really useful, but the output becomes unreadable when debugging on iOS.

**Comment by haarts** [comment]
I don't think XCode supports colors: https://stackoverflow.com/questions/40583721/print-to-console-log-with-color. 
The mentioned [XcodeColors](https://github.com/robbiehanson/XcodeColors) project seems only to work for XCode < 9.x.
Your safest best seems to pass the `colors=false` arg to the constructor.

**Comment by emersonsiega** [comment]
I'm using VSCode and have the same problem... 

![image](https://user-images.githubusercontent.com/2227499/73479867-86cd6b80-4377-11ea-926b-a8349c60e923.png)

**Comment by haarts** [comment]
Colors will never work in IDE terminals. None support ANSI escape codes. Passing `colors: false` to the constructor of `PrettyPrinter` at least gets rid of the garbage.

**Comment by kuhnroyal** [comment]
> Colors will never work in IDE terminals. None support ANSI escape codes. Passing `colors: false` to the constructor of `PrettyPrinter` at least gets rid of the garbage.

That is not completely correct, `flutter doctor` works with colors in VSCode and IntelliJ. So it seems like some double encoding or escaping is happening.

**Comment by robrichardson13** [comment]
I'm not sure why, but on one project the colors work perfectly, but on another, they don't work. I haven't figured out the difference yet.

**Comment by nemoryoliver** [comment]
Same problem for me. Hoping for a fix soon...

**Comment by daverin** [comment]
Has anyone figured this out?

**Comment by aliak00** [comment]
This seems to be an issue in the flutter library, not logger: https://github.com/flutter/flutter/issues/20663

**Comment by yushihang** [comment]
This issue is a bit complex, but we could solve it by changing logger/outputs/console_output.dart to below:

import 'dart:io';
import 'dart:developer' as developer;
import 'package:flutter/foundation.dart';
import 'package:idealab/plugins/logger/log_output.dart';
import 'package:idealab/plugins/logger/logger.dart';

const bool _kReleaseMode = kReleaseMode;
/// Default implementation of [LogOutput].
///
/// It sends everything to the system console.
class ConsoleOutput extends LogOutput {
@OverRide
void output(OutputEvent event) {
if (_kReleaseMode || !Platform.isIOS )
{
event.lines.forEach(debugPrint);
}
else
{
event.lines.forEach(developer.log);
}

}
}

**Comment by jacobokoenig** [comment]
Is there any news on this point? I'd love to have colored outputs using VSCode. Maybe there's a plugin to fix that?

**Comment by haarts** [comment]
A plugin in VSCode that would enable ASNI colors would work indeed.

**Comment by Espero1995** [comment]
> This issue is a bit complex, but we could solve it by changing logger/outputs/console_output.dart to below:
> 
> import 'dart:io'; import 'dart:developer' as developer; import 'package:flutter/foundation.dart'; import 'package:idealab/plugins/logger/log_output.dart'; import 'package:idealab/plugins/logger/logger.dart';
> 
> const bool _kReleaseMode = kReleaseMode; /// Default implementation of [LogOutput]. /// /// It sends everything to the system console. class ConsoleOutput extends LogOutput { @OverRide void output(OutputEvent event) { if (_kReleaseMode || !Platform.isIOS ) { event.lines.forEach(debugPrint); } else { event.lines.forEach(developer.log); }
> 
> } }

Nice, This method successfully solves the problem of no color in iOS. You should save this file, and run again, then it will take effect.

**Comment by strongwill01** [comment]
![image](https://user-images.githubusercontent.com/61268769/182748140-c49f1312-6062-4a41-b6f2-05205bb6dc69.png)


This is my message output.

**Comment by xiaoLit** [comment]
> ![image](https://user-images.githubusercontent.com/61268769/182748140-c49f1312-6062-4a41-b6f2-05205bb6dc69.png)
> 
> ```
> flutter: \^[[38;5;12mThis, eg[statusCode]: 200<…>
> flutter: \^[[38;5;12mThis, eg[statusMessage]: OK<…>
> ```
> 
> This is my message output.

same to me

**Comment by Thaimay** [comment]
> This issue is a bit complex, but we could solve it by changing logger/outputs/console_output.dart to below:
> 
> import 'dart:io'; import 'dart:developer' as developer; import 'package:flutter/foundation.dart'; import 'package:idealab/plugins/logger/log_output.dart'; import 'package:idealab/plugins/logger/logger.dart';
> 
> const bool _kReleaseMode = kReleaseMode; /// Default implementation of [LogOutput]. /// /// It sends everything to the system console. class ConsoleOutput extends LogOutput { @OverRide void output(OutputEvent event) { if (_kReleaseMode || !Platform.isIOS ) { event.lines.forEach(debugPrint); } else { event.lines.forEach(developer.log); }
> 
> } }

![CleanShot 2022-10-24 at 09 57 06@2x](https://user-images.githubusercontent.com/11836057/197439907-f1f689a0-8a76-440a-9fb0-110bd1540dc5.png)

Thanks it works!!

**Comment by tanhnv-avnon** [comment]
> 

Thank you. It works  🚀

**Comment by friebetill** [comment]
IMHO, not 100% clear, but you have to create an object of the class `ConsoleOutput` and assign it to the `Logger` constructor.

```dart
import 'dart:developer' as developer;

import 'package:flutter/foundation.dart';
import 'package:logger/logger.dart';
import 'package:universal_io/io.dart';

Logger logger = Logger(output: ConsoleOutput());

const bool _kReleaseMode = kReleaseMode;

/// Default implementation of [LogOutput].
///
/// It sends everything to the system console.
class ConsoleOutput extends LogOutput {
  @override
  void output(OutputEvent event) {
    if (_kReleaseMode || !Platform.isIOS) {
      event.lines.forEach(debugPrint);
    } else {
      event.lines.forEach(developer.log);
    }
  }
}
```

**Comment by colbymaloy** [comment]
not sure why but this works, thanks! colors worked on android but not iOS. this fixes the logs on IOS. thanks

> IMHO, not 100% clear, but you have to create an object of the class `ConsoleOutput` and assign it to the `Logger` constructor.
> 
> ```dart
> import 'dart:developer' as developer;
> 
> import 'package:flutter/foundation.dart';
> import 'package:logger/logger.dart';
> import 'package:universal_io/io.dart';
> 
> Logger logger = Logger(output: ConsoleOutput());
> 
> /// Extends 'LogOutput' to correctly display console colors on macOS systems.
> ///
> /// The behavior is determined by the application's run mode (Release or Debug)
> /// and the operating platform (iOS or non-iOS).
> ///
> /// For more information, see: https://github.com/simc/logger/issues/1#issuecomment-1582076726
> class ConsoleOutput extends LogOutput {
>   @override
>   void output(OutputEvent event) {
>     if (kReleaseMode || !Platform.isIOS) {
>       event.lines.forEach(debugPrint);
>     } else {
>       event.lines.forEach(developer.log);
>     }
>   }
> }
> ```

**Comment by MohamedAboElM3aTy** [comment]
I want to remove this format and time from the console 
flutter: \^[[38;5;1m│ 

Has anyone known a way to remove it?
