### ISSUE TITLE
Gradle error when trying to run my app

### ISSUE THREAD

**Issue by indeednt** [leisim/logger#7]
I got this error the first time i tried to run with the plugin logger_flutter and logger. But when I removed the logger_flutter package from pubspec.yaml and deleted the logger_flutter folder, it worked fine.
I recently migrated to AndroidX, so it could be the the cause.
```
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Windows 10 10.0 amd64
[  +11 ms] Initializing gradle... (completed in 1,3s)
[   +1 ms] Resolving dependencies...
[        ] executing: [C:\Users\Erik\Projects\apps\hazizz_mobile\android\]
C:\Users\Erik\Projects\apps\hazizz_mobile\android\gradlew.bat app:properties
[+2800 ms]
                    > Configure project :app
                    WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to
                    display a stack trace.
                    WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with
                    'variantOutput.getProcessResourcesProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the
                    command line to display a stack trace.
                    WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with
                    'variantOutput.getProcessManifestProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variantOutput.getProcessManifest(), use -Pandroid.debug.obsoleteApi=true on the
                    command line to display a stack trace.
                    WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with
                    'variant.getMergeResourcesProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command
                    line to display a stack trace.
                    WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with
                    'variant.getMergeAssetsProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line
                    to display a stack trace.
                    WARNING: API 'variant.getPackageApplication()' is obsolete and has been replaced with
                    'variant.getPackageApplicationProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the
                    command line to display a stack trace.
                    WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with
                    'variant.getExternalNativeBuildProviders()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the
                    command line to display a stack trace.
                             *********************************************************
                    WARNING: This version of android_alarm_manager will break your Android build if it or its dependencies aren't
                    compatible with AndroidX.
                             See https://goo.gl/CP92wY for more information on the problem and how to fix it.
                             This warning prints for all Android build failures. The real root cause of the error may be unrelated.
                             *********************************************************


                    FAILURE: Build failed with an exception.

                    * Where:
                    Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 245

                    * What went wrong:
                    A problem occurred configuring project ':logger_flutter'.
                    > Failed to notify project evaluation listener.
                       > Could not get unknown property 'android' for project ':logger_flutter' of type org.gradle.api.Project.
                       > Could not find method debugProvided() for arguments [file collection] on object of type
                       org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
                    Run with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 2s
[  +14 ms] Resolving dependencies... (completed in 2,8s)
[  +13 ms] * Error running Gradle:
           ProcessException: Process "C:\Users\Erik\Projects\apps\hazizz_mobile\android\gradlew.bat" exited abnormally:
           
           > Configure project :app
           WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display
a stack
           trace.
           WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with
           'variantOutput.getProcessResourcesProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command
line to
           display a stack trace.
           WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with
           'variantOutput.getProcessManifestProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variantOutput.getProcessManifest(), use -Pandroid.debug.obsoleteApi=true on the command
line to
           display a stack trace.
           WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to
display a
           stack trace.
           WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to
display a stack
           trace.
           WARNING: API 'variant.getPackageApplication()' is obsolete and has been replaced with
'variant.getPackageApplicationProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line
to display a
           stack trace.
           WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with
           'variant.getExternalNativeBuildProviders()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command
line to
           display a stack trace.
                    *********************************************************
           WARNING: This version of android_alarm_manager will break your Android build if it or its dependencies aren't compatible
with
           AndroidX.
                    See https://goo.gl/CP92wY for more information on the problem and how to fix it.
                    This warning prints for all Android build failures. The real root cause of the error may be unrelated.
                    *********************************************************
           
           
           FAILURE: Build failed with an exception.
           
           * Where:
           Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 245
           
           * What went wrong:
           A problem occurred configuring project ':logger_flutter'.
           > Failed to notify project evaluation listener.
              > Could not get unknown property 'android' for project ':logger_flutter' of type org.gradle.api.Project.
              > Could not find method debugProvided() for arguments [file collection] on object of type
              org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to
           get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 2s
             Command: C:\Users\Erik\Projects\apps\hazizz_mobile\android\gradlew.bat app:properties
           
[  +31 ms] "flutter run" took 5 327ms.
[        ] "flutter run" took 5 327ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:154:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:107:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:101:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:157:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:351:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:461:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#27     Future._complete (dart:async/future_impl.dart:473:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

```

**Comment by leisim** [comment]
🤔 This is really strange. I'll investigate it...

**Comment by haarts** [comment]
Seems stale. Closing.
